GestionCabinetAvocat/Controllers/CompteController.cs
using GestionCabinetAvocat.Autorisations;
using GestionCabinetAvocat.DAO;
using GestionCabinetAvocat.DAO.Helpers;
using GestionCabinetAvocat.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionCabinetAvocat.Controllers
{
    public class CompteController : AbstractController
    {


        [LoggedAuthorization(AllowedTypes = new String[] { "Administrateur"})]
        public ActionResult Create()
        {
            ViewBag.EmailError = "";
            ViewBag.RepeatMotDePasseError = "";

            //Create the default view model
            var compte = new Compte();
            var viewModel = new CreateAccountViewModel()
            {
                Compte = compte,
                RepeatMotDePasse = ""
            };

            return View(viewModel);
        }

        [HttpPost, LoggedAuthorization(AllowedTypes = new String[] { "Administrateur"})]
        public ActionResult Create(CreateAccountViewModel viewModel)
        {
            ViewBag.EmailError = "";
            ViewBag.RepeatMotDePasseError = "";

            //If the post informations are valid, insert the user in the database
            if (ModelState.IsValid)
            {
                var errorOccured = false;
                if (viewModel.RepeatMotDePasse != viewModel.Compte.MotDePasse)
                {
                    ViewBag.RepeatMotDePasseError = "Les mots de passes ne correspondent pas.";
                    errorOccured = true;
                }

                if (CompteHepler.Current.GetItem(viewModel.Compte.Email) != null)
                {
                    ViewBag.EmailError = "L'email renseigné existe déjà dans la base de donnée";
                    errorOccured = true;
                }

                if (!errorOccured)
                {
                    CompteHepler.Current.AddCompte(viewModel.Compte);
                    return RedirectToAction("List");
                }
            }

            return View(viewModel);
        }

        [LoggedAuthorization]
        public ActionResult List()
        {
            ViewBag.Comptes = CompteHepler.Current.GetComptes();
            return View();
        }

        [LoggedAuthorization]
        public ActionResult Detail(int id)
        {
            //Check if the user exists
            var account = CompteHepler.Current.GetItem(id);
            if (account == null)
            {
                return new HttpNotFoundResult("Le compte n'existe pas.");
            }

            return View(account);
        }

        [LoggedAuthorization(AllowedTypes = new String[] { "Administrateur"})]
        public ActionResult Edit(int id)
        {
            //Check if the user exists
            var compte = CompteHepler.Current.GetItem(id);
            if (compte == null)
            {
                return new HttpNotFoundResult("Le compte n'existe pas.");
            }

            //Create default view model
            var viewModel = new CreateAccountViewModel()
            {
                Compte = compte,
                EditRepeatMotDePasse = compte.MotDePasse,
                EditMotDePasse = compte.MotDePasse
            };
            return View(viewModel);
        }

        [HttpPost, LoggedAuthorization(AllowedTypes = new String[] { "Administrateur" })]
        public ActionResult Edit(int id, CreateAccountViewModel viewModel)
        {
            //Check if the user exists
            Compte compte = CompteHepler.Current.GetItem(id);
            if (compte == null)
            {
                return new HttpNotFoundResult("Le compte n'existe pas.");
            }

            //Force the id to the current logged user
            viewModel.Compte.Id = id;

            //If the post informations are valid, update the user informations in the database
            if (!ModelState.IsValid)
            {
                var errorOccured = false;
                if (viewModel.EditRepeatMotDePasse != null && viewModel.EditRepeatMotDePasse == viewModel.EditMotDePasse)
                {
                    viewModel.Compte.MotDePasse = viewModel.EditMotDePasse;
                }
                else
                {
                    if (viewModel.EditRepeatMotDePasse== null && viewModel.EditMotDePasse == null)
                        viewModel.Compte.MotDePasse = compte.MotDePasse;
                }
                if (viewModel.EditRepeatMotDePasse!= viewModel.EditMotDePasse)
                {
                    ViewBag.RepeatPasswordError = "Les mots de passes ne correspondent pas.";
                    errorOccured = true;
                }

                if (CompteHepler.Current.GetItem(viewModel.Compte.Email) != null && CompteHepler.Current.GetItem(viewModel.Compte.Email).Id != viewModel.Compte.Id)
                {
                    ViewBag.EmailError = "L'email renseigné existe déjà dans la base de donnée";
                    errorOccured = true;
                }

                if (!errorOccured)
                {

                    CompteHepler.Current.Update(viewModel.Compte);
                    return RedirectToAction("List");
                }
            }

            return View(viewModel);
        }

        public ActionResult Login()
        {
            var viewModel = new LoginViewModel();
            return View(viewModel);
        }

        public ActionResult Deactivate()
        {
            return View();
        }
        [HttpPost]
        [LoggedAuthorization]
        public ActionResult Logout()
        {
            Session.Remove("User");
            return RedirectToAction("Login");
        }

    }
}

GestionCabinetAvocat/Views/Shared/_Layout.cshtml
@using GestionCabinetAvocat.Models

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Cabinet Avocat</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="wrapper">
        @if (ViewBag.LoggedUser != null)
        {
            <nav id="sidebar" class="sidebar">
                <div class="sidebar-contents ">
                    <div class="sidebar-header">
                        <h3>Navigation</h3>
                    </div>

                    <ul class="list-unstyled components">
                        @foreach (var item in (ViewBag.MenuItems as IEnumerable<ControllerActionLink>))
                        {
                            <li>
                                @Html.ActionLink(item.Text, item.Action, item.Controller)
                            </li>
                        }
                    </ul>
                </div>
            </nav>
        }

        <div class="container">
            <div class="navbar navbar-fixed-top">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">
                        <img src="~/Images/head-icon.jpg" height="64" class="d-inline-block align-top" alt="Cabinet Avocat icon"><br />
                        Cabinet Avocat
                    </a>
                </div>

                @if (ViewBag.LoggedUser != null)
                {
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#hamburger-menu-contents" aria-controls="hamburger-menu-contents"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="dark-blue-text"><i class="fa fa-bars fa-1x"></i></span>
                    </button>

                    using (Html.BeginForm("Logout", "Compte", FormMethod.Post, new { @class = "logout-form" }))
                    {
                        <button type="submit" class="logout-button"></button>
                    }

                    <!-- Collapsible content -->
                    <div class="collapse navbar-collapse hidden-md-up" id="hamburger-menu-contents">
                        <ul class="navbar-nav mr-auto">
                            @foreach (var item in (ViewBag.MenuItems as IEnumerable<ControllerActionLink>))
                            {
                                <li class="nav-item">
                                    @Html.ActionLink(item.Text, item.Action, item.Controller)
                                </li>
                            }
                        </ul>
                    </div>
                }
            </div>

            <div class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - Cabinet Avocat</p>
                </footer>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery.mask")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jquery.multiselect")
    @RenderSection("scripts", required: false)
</body>
</html>